/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_bimap;

import crypto.CryptoUtils;
import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.FactureFournisseur;
import server.Message;

/**
 *
 * @author bastin
 */
public class AppWindow extends javax.swing.JFrame {

    private ClientBIMAP client;
    
    private Date dateBegin = null;
    private Date dateEnd = null;
    private String idFournisseur = null;
    
    /**
     * Creates new form AppWindow
     */
    public AppWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Application compta");
        
        try {
            client = new ClientBIMAP(this);
        } catch (ClassNotFoundException | NoSuchProviderException | NoSuchAlgorithmException | NoSuchPaddingException | IOException | KeyStoreException | CertificateException | UnrecoverableKeyException ex) {
            Logger.getLogger(AppWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        AuthentificationDialog aw = new AuthentificationDialog(this, true, client);
        aw.setVisible(true);    
        
        if(aw.logged == false)
            System.exit(0);
        
        FacturesTable.setModel(new DefaultTableModel(new String[]{"Id", "Date facturation", "Montant", "Envoyée", "Payée", "Fournisseur"}, 0));
        
         refreshFacturesFournisseurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MontantTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        IdFournisseurTextField = new javax.swing.JTextField();
        EmissionFacturesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FactureTextArea = new javax.swing.JTextArea();
        RecupererDerniereFactureButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IdFactureTextField = new javax.swing.JTextField();
        ValiderFactureButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FacturesAEviteesTextField = new javax.swing.JTextField();
        EnvoyerFacturesButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FacturesTable = new javax.swing.JTable();
        ListerFacturesButton = new javax.swing.JButton();
        DateFinTextField = new javax.swing.JFormattedTextField();
        DateDebutTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdFournisseurLabel = new javax.swing.JLabel();
        IdFournisseur2TextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        WagesMenuItem = new javax.swing.JMenuItem();

        jLabel7.setText("jLabel7");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Obtention de la plus ancienne facture non validée : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Emission d'une facture : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Validation d'une facture (noter comme payée) : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Liste de factures  : ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Ordre d'envoie de factures à payer par le comptable : ");

        MontantTextField.setPreferredSize(new java.awt.Dimension(250, 22));

        jLabel13.setText("Montant : ");

        jLabel14.setText("ID fournisseur : ");

        EmissionFacturesButton.setText("Emettre la facture");
        EmissionFacturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmissionFacturesButtonActionPerformed(evt);
            }
        });

        FactureTextArea.setColumns(20);
        FactureTextArea.setRows(5);
        jScrollPane1.setViewportView(FactureTextArea);

        RecupererDerniereFactureButton.setText("Récupérer la facture");
        RecupererDerniereFactureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecupererDerniereFactureButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Numéro de la facture : ");

        ValiderFactureButton.setText("Valider la facture");
        ValiderFactureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderFactureButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Factures à éviter : ");

        EnvoyerFacturesButton.setText("Envoyer les factures");
        EnvoyerFacturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvoyerFacturesButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(FacturesTable);

        ListerFacturesButton.setText("Obtenir les factures");
        ListerFacturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListerFacturesButtonActionPerformed(evt);
            }
        });

        DateFinTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        DateDebutTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel5.setText("Date début : ");

        jLabel6.setText("Date fin : ");

        IdFournisseurLabel.setText("Identifiant fournisseur :");

        Menu.setText("Menu");

        WagesMenuItem.setText("Gestion des salaires");
        WagesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WagesMenuItemActionPerformed(evt);
            }
        });
        Menu.add(WagesMenuItem);

        jMenuBar1.add(Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(EmissionFacturesButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdFournisseurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdFactureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(ValiderFactureButton)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnvoyerFacturesButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FacturesAEviteesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RecupererDerniereFactureButton))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ListerFacturesButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(IdFournisseurLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateFinTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(DateDebutTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(IdFournisseur2TextField))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(MontantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDebutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(IdFournisseurTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(DateFinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmissionFacturesButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IdFournisseurLabel)
                        .addComponent(IdFournisseur2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(ListerFacturesButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RecupererDerniereFactureButton)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IdFactureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ValiderFactureButton)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(FacturesAEviteesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(EnvoyerFacturesButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListerFacturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListerFacturesButtonActionPerformed
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        
        if(DateDebutTextField.getText().equals(""))
            dateBegin = null;
        else
        {
            try {
                dateBegin = formatter.parse(DateDebutTextField.getText());
            } catch (ParseException ex) {
                dateBegin = null;
                JOptionPane.showMessageDialog(this, "Format de la date début invalide");
            }            
        }
        
        if(DateFinTextField.getText().equals(""))
            dateEnd = null;
        else
        {
            try {  
                dateEnd = formatter.parse(DateFinTextField.getText()); 
            } catch (ParseException ex) {
                dateEnd = null;
                JOptionPane.showMessageDialog(this, "Format de la date de fin invalide");
            }            
        }
                
        if(IdFournisseur2TextField.getText().equals(""))
            idFournisseur = null;
        else
            idFournisseur = IdFournisseur2TextField.getText();
        
        refreshFacturesFournisseurs();
    }//GEN-LAST:event_ListerFacturesButtonActionPerformed

    public void refreshFacturesFournisseurs()
    {
        Message response = client.listBills(dateBegin, dateEnd, idFournisseur);
        
        if(response.hasParam("error"))
            JOptionPane.showMessageDialog(this, response.getParam("error"));
        else
        {
            DefaultTableModel dtm = (DefaultTableModel) FacturesTable.getModel();
            
            dtm.setRowCount(0);
            
            ArrayList<FactureFournisseur> data = (ArrayList) response.getParam("data");
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            data.forEach((row) -> {
                dtm.addRow(new Object[]{row.getIdFacture(), dateFormat.format(row.getDateFacturation()), row.getMontant(), row.getEnvoyee(), row.getPayee(), row.getFournisseur().getNom()});
            });
        }        
    }
    
    private void EmissionFacturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmissionFacturesButtonActionPerformed
        float montant = Float.parseFloat(MontantTextField.getText());
        int idFournisseur = Integer.parseInt(IdFournisseurTextField.getText());
        
        Message response = client.makeBill(montant, idFournisseur);
        
        if(response.hasParam("error"))
            JOptionPane.showMessageDialog(this, response.hasParam("error"));
        else
        {
            MontantTextField.setText("");
            IdFournisseurTextField.setText("");
            refreshFacturesFournisseurs();
            JOptionPane.showMessageDialog(this, "Facture émise");            
        }
    }//GEN-LAST:event_EmissionFacturesButtonActionPerformed

    private void RecupererDerniereFactureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecupererDerniereFactureButtonActionPerformed
        FactureFournisseur ff = client.nextBill();

        if(ff != null)
        {
            FactureTextArea.setText("");

            FactureTextArea.append(
                    "ID facture: " + ff.getIdFacture() + "\n" +
                    "Date facturation: " + ff.getDateFacturation() + "\n" + 
                    "Montant: " + ff.getMontant() + "\n" + 
                    "Envoyée: " + ff.getEnvoyee() + "\n" +
                    "Payée: " + ff.getPayee() + "\n" + 
                    "ID fournisseur: " + ff.getFournisseur().getIdFournisseur() + "\n" + 
                    "Nom fournisseur: " + ff.getFournisseur().getNom() 
            );
        }
    }//GEN-LAST:event_RecupererDerniereFactureButtonActionPerformed

    private void ValiderFactureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderFactureButtonActionPerformed
        if(IdFactureTextField.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Veuillez indiquer l'id d'une facture");
        else
        {
            int idFacture = Integer.valueOf(IdFactureTextField.getText());
        
            Message response = client.validateBill(idFacture);

            if(response.hasParam("error"))
                JOptionPane.showMessageDialog(this, response.getParam("error"));
            else
            {
                if(response.hasParam("ret"))
                    JOptionPane.showMessageDialog(this, response.getParam("ret"));
                else
                    JOptionPane.showMessageDialog(this, "Facture notée comme payée");
                
                IdFactureTextField.setText("");
                refreshFacturesFournisseurs();
            }           
        }
        

    }//GEN-LAST:event_ValiderFactureButtonActionPerformed

    private void EnvoyerFacturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvoyerFacturesButtonActionPerformed
        String facturesAEvitees = FacturesAEviteesTextField.getText();
        
        Message response = client.sendBills(facturesAEvitees);
        
        if(response.hasParam("error"))
            JOptionPane.showMessageDialog(this, response.getParam("error"));
        else
        {
            JOptionPane.showMessageDialog(this, "Opération effectuée");
            refreshFacturesFournisseurs();
        }
    }//GEN-LAST:event_EnvoyerFacturesButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        client.interrupt();
    }//GEN-LAST:event_formWindowClosing

    private void WagesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WagesMenuItemActionPerformed
        new WindowWAPP(this).setVisible(true);
    }//GEN-LAST:event_WagesMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DateDebutTextField;
    private javax.swing.JFormattedTextField DateFinTextField;
    private javax.swing.JButton EmissionFacturesButton;
    private javax.swing.JButton EnvoyerFacturesButton;
    private javax.swing.JTextArea FactureTextArea;
    private javax.swing.JTextField FacturesAEviteesTextField;
    private javax.swing.JTable FacturesTable;
    private javax.swing.JTextField IdFactureTextField;
    private javax.swing.JTextField IdFournisseur2TextField;
    private javax.swing.JLabel IdFournisseurLabel;
    private javax.swing.JTextField IdFournisseurTextField;
    private javax.swing.JButton ListerFacturesButton;
    private javax.swing.JMenu Menu;
    private javax.swing.JTextField MontantTextField;
    private javax.swing.JButton RecupererDerniereFactureButton;
    private javax.swing.JButton ValiderFactureButton;
    private javax.swing.JMenuItem WagesMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
