/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_dismap;

import models.TypePrecis;
import models.Ville;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import server.Message;

/**
 *
 * @author bastin
 */
public class PaymentWindow extends javax.swing.JDialog {
    
    protected ClientDISMAP client;
    protected int sumBasket;
    protected boolean paid = false;

    /**
     * Creates new form PaymentWindow
     */
    public PaymentWindow(ClientDISMAP client, int sumBasket) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
         
        this.client = client;
        this.sumBasket = sumBasket;
        
        populateVilles();
        
        SumBasketLabel.setText(String.valueOf(this.sumBasket) + " €");
    }
    
    private void populateVilles() {
        ArrayList<Ville> villes = client.listVilles();
        
        Ville ville = new Ville();
        ville.setIdVille(0);
        ville.setNom("Sélectionnez une ville");
        
        villes.add(0, ville);
        
        CityComboBox.setModel(new DefaultComboBoxModel(new Vector(villes))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliveryButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PaymentModeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ConfirmOrderButton = new javax.swing.JButton();
        SumBasketLabel = new javax.swing.JLabel();
        CancelOrderButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DeliveryNowRadioButton = new javax.swing.JRadioButton();
        DeliveryAskRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CityComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Paiement : ");

        jLabel2.setText("Mode de paiement : ");

        PaymentModeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionnez", "Liquide", "Virement", "Chèque", "Carte" }));

        jLabel3.setText("Montant total : ");

        ConfirmOrderButton.setText("Confirmer la commande");
        ConfirmOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmOrderButtonActionPerformed(evt);
            }
        });

        SumBasketLabel.setText("000");

        CancelOrderButton.setText("Annuler");
        CancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Livraison : ");

        deliveryButtonGroup.add(DeliveryNowRadioButton);
        DeliveryNowRadioButton.setSelected(true);
        DeliveryNowRadioButton.setText("Livraison immédiate");
        DeliveryNowRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryNowRadioButtonActionPerformed(evt);
            }
        });

        deliveryButtonGroup.add(DeliveryAskRadioButton);
        DeliveryAskRadioButton.setText("Demande de livraison");
        DeliveryAskRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryAskRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Adresse : ");

        AddressTextField.setEnabled(false);

        jLabel6.setText("Ville : ");

        CityComboBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConfirmOrderButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DeliveryNowRadioButton)
                            .addGap(35, 35, 35)
                            .addComponent(DeliveryAskRadioButton))
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SumBasketLabel)
                                .addComponent(PaymentModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddressTextField)
                                .addComponent(CityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PaymentModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SumBasketLabel))
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeliveryAskRadioButton)
                    .addComponent(DeliveryNowRadioButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmOrderButton)
                    .addComponent(CancelOrderButton))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeliveryNowRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryNowRadioButtonActionPerformed
        updateDelivery();
    }//GEN-LAST:event_DeliveryNowRadioButtonActionPerformed

    private void DeliveryAskRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryAskRadioButtonActionPerformed
        updateDelivery();
    }//GEN-LAST:event_DeliveryAskRadioButtonActionPerformed

    private void CancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelOrderButtonActionPerformed

    private void ConfirmOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmOrderButtonActionPerformed
        
        String modePayment = "";

        switch(PaymentModeComboBox.getSelectedIndex())
        {
            case 1:
                modePayment = "LIQUIDE";
                break;
            case 2:
                modePayment = "VIREMENT";
                break;
            case 3:
                modePayment = "CHEQUE";
                break;
            case 4:
                modePayment = "BANCONTACT";
                break;
        }
        
        if(modePayment.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Veuillez indiquer un mode paiement");
            return;
        }
        
        Message response;
        
        if(DeliveryNowRadioButton.isSelected())
        {
            response = client.executeOrder(modePayment, null, 0);
        }
        else
        {
            String address = AddressTextField.getText();
            Ville ville = (Ville) CityComboBox.getSelectedItem();
            
            if(ville.getIdVille() == 0)
            {
                JOptionPane.showMessageDialog(this, "Veuillez indiquer une ville");
                return;
            }
        
            response = client.executeOrder(modePayment, address, ville.getIdVille());
        }
        
        if(response.hasParam("error"))
            JOptionPane.showMessageDialog(this, response.getParam("error"));
        else if(response.hasParam("refusal"))
            JOptionPane.showMessageDialog(this, response.getParam("refusal"));
        else
        {
            paid = true;
            JOptionPane.showMessageDialog(this, "Votre commande a été effectuté !");
            dispose();
        }     
    }//GEN-LAST:event_ConfirmOrderButtonActionPerformed

    public boolean isOrderPaid() {
        return paid;
    }
    
    private void updateDelivery() {
        if(DeliveryNowRadioButton.isSelected())
        {
            AddressTextField.setEnabled(false);
            CityComboBox.setEnabled(false);
        }
        else
        {
            AddressTextField.setEnabled(true);
            CityComboBox.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton CancelOrderButton;
    private javax.swing.JComboBox<String> CityComboBox;
    private javax.swing.JButton ConfirmOrderButton;
    private javax.swing.JRadioButton DeliveryAskRadioButton;
    private javax.swing.JRadioButton DeliveryNowRadioButton;
    private javax.swing.JComboBox<String> PaymentModeComboBox;
    private javax.swing.JLabel SumBasketLabel;
    private javax.swing.ButtonGroup deliveryButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
