/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_indep;

import java.awt.BorderLayout;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import server.Message;

/**
 *
 * @author florentcardoen
 */
public class VENTES_COMP extends javax.swing.JPanel {
    ClientINDEP client;
    /**
     * Creates new form VENTES_COMP
     */
    public VENTES_COMP() {
        initComponents();
        yearSpinner.setEditor(new JSpinner.DateEditor(yearSpinner, "yyyy"));
        descrLabel.setText("Dernière année prise en compte :");

    }
    public void setClient(ClientINDEP cli)
    {
        client = cli;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        yearSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        dixRadio = new javax.swing.JRadioButton();
        unRadio = new javax.swing.JRadioButton();
        chartPane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        descrLabel = new javax.swing.JLabel();

        yearSpinner.setModel(new javax.swing.SpinnerDateModel());

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Comparaison des ventes");

        buttonGroup1.add(dixRadio);
        dixRadio.setSelected(true);
        dixRadio.setText("10 dernières années");
        dixRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dixRadioStateChanged(evt);
            }
        });
        dixRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dixRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(unRadio);
        unRadio.setText("Année précise");
        unRadio.setToolTipText("");
        unRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                unRadioStateChanged(evt);
            }
        });

        javax.swing.GroupLayout chartPaneLayout = new javax.swing.GroupLayout(chartPane);
        chartPane.setLayout(chartPaneLayout);
        chartPaneLayout.setHorizontalGroup(
            chartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartPaneLayout.setVerticalGroup(
            chartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jButton1.setText("Let's go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        descrLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(unRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(descrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(dixRadio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(chartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dixRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unRadio)
                    .addComponent(jButton1)
                    .addComponent(descrLabel)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dixRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dixRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dixRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Integer annee, nbr;
        String str;
        Message response;
        HashMap data;
        
        Calendar cal = Calendar.getInstance();
        cal.setTime((Date)yearSpinner.getValue());
        annee = cal.get(Calendar.YEAR);
        if(dixRadio.isSelected()){
            nbr = 10;
        }
        else
        {
            nbr = 1;
        }
        
        response = client.Ventes_comp(annee, nbr);
        
        if((Integer)response.getParam("status") == 0)
            JOptionPane.showMessageDialog(this,response.getParam("error"),"Erreur interne", JOptionPane.ERROR_MESSAGE);
        else
        {
            DefaultCategoryDataset ds = new DefaultCategoryDataset();

            if(dixRadio.isSelected())
            {
                str = "Ventes des "+nbr+" dernières années jusque " + annee;
                for (Integer i = (annee-9); i <= annee; i++)
                {
                   ds.setValue((Double)response.getParam(i.toString()), "montant", i); 
                }
            }
            else
            {
                str = "Ventes de l'année " + annee;
                String[] mois = {"Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Aout", "Septembre","Octobre", "Novembre","Décembre"};
                for (Integer i = 1; i <= 12; i++)
                {
                   ds.setValue((Double)response.getParam(i.toString()), "montant", mois[i-1]); 
                }
            }
            

            JFreeChart jfc = ChartFactory.createBarChart(str, "Total", "Montant", ds, PlotOrientation.VERTICAL,true, true, false);
            
            ChartPanel cp = new ChartPanel(jfc);
            //chartPane = new JPanel();
            chartPane.setLayout(new java.awt.BorderLayout());
            chartPane.add(cp);
            chartPane.setVisible(true);
            chartPane.validate();
            //System.out.println((Integer)response.getParam("status"));
        }
    }                                        

    private void genButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dixRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dixRadioStateChanged
        descrLabel.setText("Dernière année prise en compte :");
    }//GEN-LAST:event_dixRadioStateChanged

    private void unRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_unRadioStateChanged
        // TODO add your handling code here:
        descrLabel.setText("Année prise en compte :");

    }//GEN-LAST:event_unRadioStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chartPane;
    private javax.swing.JLabel descrLabel;
    private javax.swing.JRadioButton dixRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton unRadio;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
